//
//  FriendsDebtModels.swift
//  Macro Challenge ADAIL
//
//  Created by Santo Michael Sihombing on 19/11/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct Debt {
    let userId: String
    let friendsId: String
    let total: Int
}

struct DebtHistory {
    let DebtId: String
    let userId: String
    let friendsId: String
    let totalDebt: Int
    let date: Date
}

struct PaidHistory {
    let DebtId: String
    let userId: String
    let friendsId: String
    let totalpaid: Int
    let date: Date
}
